workspace:
  base: /go
  path: src/github.com/smford/drone-test-repo-1

pipeline:
  build:
    image: golang:latest
    commands:
      - ls -la 
      - echo "hello world" 
      - go version
      - go get -u github.com/golang/dep/cmd/dep
      - git clone https://github.com/smford/narcotk-hosts.git
      - cd narcotk-hosts
      - dep ensure
      - go build -o narcotk-hosts main.go
      - ./narcotk-hosts --setupdb --database=./new-database-file.db
